apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: memcached
  namespace: monitoring
  labels:
    app: memcached

spec:
  selector:
    matchLabels:
      app: memcached
  maxUnavailable: 1
