apiVersion: v1
kind: Service
metadata:
  name: memcached
  namespace: monitoring
spec:
  clusterIP: None
  ports:
  - name: memcached-client
    port: 11211
    protocol: TCP
    targetPort: 11211
  - name: exporter
    port: 9106
    protocol: TCP
    targetPort: 9106
  selector:
    app: memcached
  type: ClusterIP