apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: cortex-ingester
  namespace: monitoring
  labels:
    app: cortex
    component: ingester

spec:
  selector:
    matchLabels:
      app: cortex
      component: ingester
  maxUnavailable: 1