global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  scrape_timeout: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'cortex'
    tls_config:
      insecure_skip_verify: true
    params:
      format: ['prometheus']
    kubernetes_sd_configs:
    - role: pod
      namespaces:
        names:
          - monitoring
    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_label_app,__meta_kubernetes_pod_annotation_prometheus_io_scrape]
      action: keep
      regex: cortex;true
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
      action: replace
      target_label: __metrics_path__
      regex: (.+)
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scheme]
      action: replace
      target_label: __scheme__
      regex: (https?)
    - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
      action: replace
      regex: ([^:]+)(?::\d+)?;(\d+)
      replacement: $1:$2
      target_label: __address__
    - action: labelmap
      regex: __meta_kubernetes_pod_label_(.+)
    - source_labels: [__meta_kubernetes_namespace]
      action: replace
      target_label: kubernetes_namespace
    - source_labels: [__meta_kubernetes_pod_name]
      action: replace
      target_label: kubernetes_pod_name
