apiVersion: v1
kind: Service
metadata:
  name: cortex-distributor
  namespace: monitoring
spec:
  ports:
  - name: distributor
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: cortex
    component: distributor
  sessionAffinity: None
  type: ClusterIP