# You must create a service account in the IAM which has bigtable.admin permissions.
# Then you can put the service account's JSON as secret into your cluster and mount it
# into your pods (see other deployment yamls).
#
# The service account must be used by all services interacting with BigTable:
# Table Manager, Ingester, Querier
apiVersion: v1
kind: Secret
type: Opaque
data:
  credentials.json: xyz
metadata:
  name: sa-cortex
  namespace: monitoring