apiVersion: v1
kind: Service
metadata:
  name: cortex-query-frontend-headless
  namespace: monitoring
spec:
  selector:
    app: cortex
    component: query-frontend
  clusterIP: None
  ports:
  - name: http
    port: 80
  - name: grpc
    port: 9095
