apiVersion: v1
kind: Service
metadata:
  name: cortex-query-frontend
  namespace: monitoring
spec:
  selector:
    app: cortex
    component: query-frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: grpc
    port: 9095
    targetPort: 9095
