apiVersion: v1
kind: ConfigMap
metadata:
  name: tenant-limit-config
  namespace: monitoring
data:
  config.yaml: |-
    overrides:
      rd-bigdata-prd-bigdata:
        ingestion_rate: 300000
        ingestion_burst_size: 600000
        max_series_per_metric: 40000
        max_series_per_user: 1000000