apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: jaeger
    component: collector
  name: jaeger-collector
  namespace: monitoring
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jaeger
      component: collector
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "14269"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: jaeger
        component: collector
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - jaeger
                - key: component
                  operator: In
                  values:
                  - collector
              topologyKey: failure-domain.beta.kubernetes.io/zone
            weight: 100
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - jaeger
                - key: component
                  operator: In
                  values:
                  - collector
              topologyKey: kubernetes.io/hostname
            weight: 20
      containers:
      - env:
        - name: SPAN_STORAGE_TYPE
          value: elasticsearch
        - name: ES_SERVER_URLS
          value: https://tracing-es.monitoring.svc.cluster.local:9200
        - name: ES_TLS_CA
          value: /etc/jaeger/elasticsearch-certs/ca.pem
        - name: COLLECTOR_PORT
          value: "14267"
        - name: COLLECTOR_HTTP_PORT
          value: "14268"
        - name: COLLECTOR_ZIPKIN_HTTP_PORT
          value: "9411"
        image: jaegertracing/jaeger-collector:1.12.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: health
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: collector
        ports:
        - containerPort: 14267
          name: thrift-spans
          protocol: TCP
        - containerPort: 14250
          name: proto-spans
          protocol: TCP
        - containerPort: 14268
          name: binary-spans
          protocol: TCP
        - containerPort: 9411
          name: zipkin-spans
          protocol: TCP
        - containerPort: 14269
          name: health
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: health
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "2"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 300Mi
        volumeMounts:
        - mountPath: /etc/jaeger/elasticsearch-certs
          name: elasticsearch-certs
      dnsPolicy: ClusterFirst
      volumes:
      - name: elasticsearch-certs
        secret:
          defaultMode: 420
          optional: false
          secretName: tracing-ca